In [161]:
import pandas as pd

dialog_train = pd.read_csv('train.csv', usecols=['dialog_id','speaker','da_tag', 'start_time', 'end_time'])
dialog_valid = pd.read_csv('valid.csv', usecols=['dialog_id','speaker','da_tag', 'start_time', 'end_time'])
dialog_test= pd.read_csv('test.csv', usecols=['dialog_id','speaker','da_tag', 'start_time', 'end_time'])

In [162]:
dialog_train.reset_index(inplace=True)
dialog_valid.reset_index(inplace=True)
dialog_test.reset_index(inplace=True)

In [164]:
dialog_train = dialog_train[dialog_train['da_tag'].isin(["sd", "b", "sv", "aa", "%", "ba", "qy", "x", "ny", "fc"])]
dialog_valid = dialog_valid[dialog_valid['da_tag'].isin(["sd", "b", "sv", "aa", "%", "ba", "qy", "x", "ny", "fc"])]
dialog_test = dialog_valid[dialog_valid['da_tag'].isin(["sd", "b", "sv", "aa", "%", "ba", "qy", "x", "ny", "fc"])]

In [166]:
dialog_train

       index dialog_id speaker da_tag  start_time   end_time
1          1    sw2005       B      x     0.00000   10.94882
3          3    sw2005       A      x    10.93013   21.35084
4          4    sw2005       B     sv    10.94882   22.28000
5          5    sw2005       A      b    21.35084   22.08088
6          6    sw2005       A      x    22.08088   44.96288
...      ...       ...     ...    ...         ...        ...
83966  83966    sw4940       A     ny   294.59659  295.00000
83967  83967    sw4940       B     sd   294.62349  297.66445
83968  83968    sw4940       A      x   295.00000  298.58336
83969  83969    sw4940       B      x   297.66445  299.88000
83970  83970    sw4940       A     sd   298.58336  299.88000

[74111 rows x 6 columns]

In [ ]:
from pydub import AudioSegment

for index, row in dialog_train.iterrows():
    file_name = row['dialog_id'] + '_' + row['speaker'] + '.wav'
    full_path = os.path.join('wav', file_name)
    if os.path.exists(full_path):
        audio = AudioSegment.from_wav(full_path)
        start_time = int(row['start_time'] * 1000)  
        end_time = int(row['end_time'] * 1000) 

        segment = audio[start_time:end_time]
        segment.export(f"segment/{file_name}_{index}.wav", format="wav")

In [132]:
from pydub import AudioSegment

for index, row in dialog_valid.iterrows():
    file_name = row['dialog_id'] + '_' + row['speaker'] + '.wav'
    full_path = os.path.join('wav', file_name)
    if os.path.exists(full_path):
        audio = AudioSegment.from_wav(full_path)
        start_time = int(row['start_time'] * 1000)  
        end_time = int(row['end_time'] * 1000) 

        segment = audio[start_time:end_time]
        segment.export(f"valid_segment/{file_name}_{index}.wav", format="wav")

In [86]:
from pydub import AudioSegment

for index, row in dialog_test.iterrows():
    file_name = row['dialog_id'] + '_' + row['speaker'] + '.wav'
    full_path = os.path.join('wav', file_name)
    if os.path.exists(full_path):
        audio = AudioSegment.from_wav(full_path)
        start_time = int(row['start_time'] * 1000)  
        end_time = int(row['end_time'] * 1000) 

        segment = audio[start_time:end_time]
        segment.export(f"test_segment/{file_name}_{index}.wav", format="wav")

In [111]:
import os
import opensmile  
import pandas as pd  
import re

smile = opensmile.Smile(
    feature_set=opensmile.FeatureSet.eGeMAPSv01a,
    feature_level=opensmile.FeatureLevel.Functionals
)

wav_files = [f for f in os.listdir('segment') if f.endswith('.wav')]

features_df = pd.DataFrame()

for file in wav_files:
    full_path = os.path.join('segment', file)
    #features = smile.process_file(full_path)
    index = int(re.findall(r'\d+', file)[-1])
    da_tag = dialog_train[dialog_train['index'] == index].da_tag.values[0]
    features_df = pd.concat([features_df, features.assign(index=index, da_tag=da_tag)])

/Users/zarahall/miniconda3/envs/torch/lib/python3.10/site-packages/opensmile/core/smile.py:251: UserWarning: Feature set 'FeatureSet.eGeMAPS' is deprecated, consider switching to 'FeatureSet.eGeMAPSv02'.
  warnings.warn(

KeyboardInterrupt:

In [158]:
features_df4 = pd.DataFrame()
wav_files = [f for f in os.listdir('test_segment') if f.endswith('.wav')]

for file in wav_files:
    index = int(re.findall(r'\d+', file)[-1])
    da_tag = dialog_test[dialog_test['index'] == index]
    features_df4 = pd.concat([features_df4, da_tag])

In [172]:
features_df4

       index dialog_id speaker  da_tag  start_time    end_time
5101    5101    sw2295       B     NaN    32.63330   33.060710
16999  16999    sw3815       A     NaN     9.51920   10.613330
9891    9891    sw2932       A     NaN   381.57403  388.393920
23262  23262    sw4908       B     NaN    86.66595   95.451980
23126  23126    sw4814       A     NaN    98.57013  104.390400
...      ...       ...     ...     ...         ...         ...
5118    5118    sw2295       B     NaN    63.48000   71.389860
5364    5364    sw2380       A     NaN   125.88000  131.862021
22301  22301    sw4688       A     NaN   281.12587  281.279020
9632    9632    sw2876       B     NaN   171.33639  171.613020
1958    1958    sw2085       A     NaN   294.84306  302.955300

[23540 rows x 6 columns]

In [171]:
features_df4.to_csv('test_index.csv', index=False)

In [167]:
dialog_train

       index dialog_id speaker da_tag  start_time   end_time
1          1    sw2005       B      x     0.00000   10.94882
3          3    sw2005       A      x    10.93013   21.35084
4          4    sw2005       B     sv    10.94882   22.28000
5          5    sw2005       A      b    21.35084   22.08088
6          6    sw2005       A      x    22.08088   44.96288
...      ...       ...     ...    ...         ...        ...
83966  83966    sw4940       A     ny   294.59659  295.00000
83967  83967    sw4940       B     sd   294.62349  297.66445
83968  83968    sw4940       A      x   295.00000  298.58336
83969  83969    sw4940       B      x   297.66445  299.88000
83970  83970    sw4940       A     sd   298.58336  299.88000

[74111 rows x 6 columns]

In [ ]:
import os
import opensmile  
import pandas as pd  
import re

smile = opensmile.Smile(
    feature_set=opensmile.FeatureSet.eGeMAPSv01a,
    feature_level=opensmile.FeatureLevel.Functionals
)

wav_files = [f for f in os.listdir('valid_segment') if f.endswith('.wav')]

valid_features_df = pd.DataFrame()

for file in wav_files:
    full_path = os.path.join('valid_segment', file)
    features = smile.process_file(full_path)
    index = int(re.findall(r'\d+', file)[-1])
    da_tag = dialog_valid[dialog_valid['index'] == index].da_tag.values[0]
    valid_features_df = pd.concat([valid_features_df, features.assign(index=index, da_tag=da_tag)])

In [87]:
import os
import opensmile  
import pandas as pd  
import re

smile = opensmile.Smile(
    feature_set=opensmile.FeatureSet.eGeMAPSv01a,
    feature_level=opensmile.FeatureLevel.Functionals
)

wav_files = [f for f in os.listdir('test_segment') if f.endswith('.wav')]

test_features_df = pd.DataFrame()

for file in wav_files:
    full_path = os.path.join('test_segment', file)
    features = smile.process_file(full_path)
    index = int(re.findall(r'\d+', file)[-1])
    da_tag = dialog_test[dialog_test['index'] == index].da_tag.values[0]
    features_df = pd.concat([features_df, features.assign(index=index, da_tag=da_tag)])

/Users/zarahall/miniconda3/envs/torch/lib/python3.10/site-packages/opensmile/core/smile.py:251: UserWarning: Feature set 'FeatureSet.eGeMAPS' is deprecated, consider switching to 'FeatureSet.eGeMAPSv02'.
  warnings.warn(
/Users/zarahall/miniconda3/envs/torch/lib/python3.10/site-packages/opensmile/core/smile.py:301: UserWarning: Segment too short, filling with NaN.
  warnings.warn(
/Users/zarahall/miniconda3/envs/torch/lib/python3.10/site-packages/opensmile/core/smile.py:301: UserWarning: Segment too short, filling with NaN.
  warnings.warn(
/Users/zarahall/miniconda3/envs/torch/lib/python3.10/site-packages/opensmile/core/smile.py:301: UserWarning: Segment too short, filling with NaN.
  warnings.warn(
/Users/zarahall/miniconda3/envs/torch/lib/python3.10/site-packages/opensmile/core/smile.py:301: UserWarning: Segment too short, filling with NaN.
  warnings.warn(
/Users/zarahall/miniconda3/envs/torch/lib/python3.10/site-packages/opensmile/core/smile.py:301: UserWarning: Segment too short, filling with NaN.
  warnings.warn(
/Users/zarahall/miniconda3/envs/torch/lib/python3.10/site-packages/opensmile/core/smile.py:301: UserWarning: Segment too short, filling with NaN.
  warnings.warn(
/Users/zarahall/miniconda3/envs/torch/lib/python3.10/site-packages/opensmile/core/smile.py:301: UserWarning: Segment too short, filling with NaN.
  warnings.warn(

In [107]:
features_df = features_df.iloc[:70952]

In [110]:
features_df2 = features_df[['F0semitoneFrom27.5Hz_sma3nz_amean', 'F0semitoneFrom27.5Hz_sma3nz_stddevNorm', 'loudness_sma3_amean', 'loudness_sma3_percentile20.0', 'loudness_sma3_percentile50.0', 'loudness_sma3_percentile80.0', 'spectralFlux_sma3_amean', 'mfcc1_sma3_amean', 'mfcc2_sma3_amean', 'VoicedSegmentsPerSec', 'MeanVoicedSegmentLengthSec', 'jitterLocal_sma3nz_amean', 'shimmerLocaldB_sma3nz_amean', 'HNRdBACF_sma3nz_amean', 'logRelF0-H1-H2_sma3nz_amean', 'F1frequency_sma3nz_amean', 'F2frequency_sma3nz_amean', 'F3frequency_sma3nz_amean', 'alphaRatioV_sma3nz_amean', 'hammarbergIndexV_sma3nz_amean']]

In [126]:
features_df.to_csv('speech_features_train.csv', index=False)

In [45]:
valid_features_df.to_csv('speech_features_valid', index=False)

In [105]:
test_features_df.to_csv('speech_features_test', index=False)